[build]
  base = "."
  publish = "_site"
  functions = "functions-build"
  command = "npm run build"

[dev]
  publish = "form"
  functions = "functions-build"
  port = 8888

[functions]
  node_bundler = "esbuild"

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Note: Removed problematic redirect as Netlify doesn't allow redirects
# to or from paths starting with "/.netlify" - these paths are reserved

# Handle form page
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Ensure resume pages work
[[redirects]]
  from = "/resumes/*"
  to = "/_site/resumes/:splat"
  status = 200

# Ensure edit pages work
[[redirects]]
  from = "/edit/*"
  to = "/_site/edit/:splat"
  status = 200

# Catch-all: Redirect all other requests to index.html (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  GITHUB_OWNER = "barrymjulien"
  GITHUB_REPO = "resume-website-generator"
  GITHUB_TOKEN = "Your GitHub personal access token"
