[build]
  base = "."
  publish = "form"
  functions = "lambda"
  command = "npm run build:function"

[dev]
  publish = "form"
  functions = "lambda"
  port = 8888

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/resumes/*"
  to = "https://barrymjulien.github.io/resume-website-generator/resumes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/edit/*"
  to = "https://barrymjulien.github.io/resume-website-generator/edit/:splat"
  status = 301
  force = true

[template.environment]
  GITHUB_OWNER = "barrymjulien"
  GITHUB_REPO = "resume-website-generator"
  GITHUB_TOKEN = "Your GitHub personal access token"
